import type { Metadata } from "next";
import { contact } from "@/content/site";

/**
 * Builds a page's metadata so the tags that must agree cannot drift apart.
 *
 * The bug this exists to prevent: `openGraph` was declared once in the root
 * layout, and Next merges metadata shallowly per key. A page that set only
 * `title` and `description` inherited the parent's ENTIRE openGraph object
 * untouched — so every page on the site shared the homepage's og:title,
 * og:description and og:url. The `<title>` tag was correct the whole time,
 * which is why nobody noticed: browsers read `<title>`, but SMS, iMessage,
 * Slack and LinkedIn read Open Graph.
 *
 * Next does NOT derive og:title from the page title. It has to be set, and
 * setting it per page by hand is the thing everyone forgets. Hence one
 * function that emits all of it together.
 *
 * `og:title` is the page's own title WITHOUT her name appended, unlike the
 * `<title>` tag. A shared link gets about three lines in a chat app, and the
 * distinguishing words should be in them; her name is already carried by
 * `og:site_name` and the domain.
 *
 * `robots` is only set for noindex pages. Everything else must inherit the
 * root layout's production check — hardcoding `index: true` here would make
 * staging crawlable, which is the failure site-config.ts exists to prevent.
 */
/**
 * Generated by src/app/opengraph-image.tsx and emitted to /opengraph-image.
 * Resolved against `metadataBase` from the root layout, so it becomes
 * absolute in the rendered tag — which scrapers require.
 */
const OG_IMAGE = "/opengraph-image";

export function pageMetadata({
  title,
  description,
  path,
  noindex = false,
  follow = false,
}: {
  title: string;
  description: string;
  /** Route path, no trailing slash. Use "/" for the homepage. */
  path: string;
  noindex?: boolean;
  /**
   * Only read when `noindex` is set. The confirmation pages allow following
   * so link equity still flows through them; `/admin` does not, because
   * nothing behind the gate should be discovered at all.
   */
  follow?: boolean;
}): Metadata {
  // trailingSlash: true — the canonical and og:url must match what is served.
  const url = path === "/" ? "/" : `${path}/`;

  return {
    title,
    description,
    alternates: { canonical: url },
    openGraph: {
      title,
      description,
      url,
      siteName: contact.name,
      locale: "en_US",
      type: "website",
      // Named explicitly, and it must be. The opengraph-image.tsx convention
      // injects itself into the root layout's openGraph object, but a page
      // that declares its own openGraph REPLACES the parent's rather than
      // merging into it — so every page below the root silently lost og:image
      // until this line existed. Verified in the built HTML, not assumed.
      images: [OG_IMAGE],
    },
    twitter: {
      // summary_large_image, not summary: LinkedIn and iMessage render a wide
      // card, and a link with no picture is a visibly weaker post.
      card: "summary_large_image",
      title,
      description,
      images: [OG_IMAGE],
    },
    ...(noindex ? { robots: { index: false, follow } } : {}),
  };
}
